// <auto-generated />
namespace EFarming.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddCooperatives : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCooperatives));
        
        string IMigrationMetadata.Id
        {
            get { return "201405312335596_AddCooperatives"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
