// <auto-generated />
namespace EFarming.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Change_PricesDate_Format_From_Date_To_String : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_PricesDate_Format_From_Date_To_String));
        
        string IMigrationMetadata.Id
        {
            get { return "201510161537108_Change_PricesDate_Format_From_Date_To_String"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
