// <auto-generated />
namespace EFarming.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _26May : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_26May));
        
        string IMigrationMetadata.Id
        {
            get { return "201505261509398_26May"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
