// <auto-generated />
namespace EFarming.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Changing_PhoneNumber_To_Long : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changing_PhoneNumber_To_Long));
        
        string IMigrationMetadata.Id
        {
            get { return "201607122134161_Changing_PhoneNumber_To_Long"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
