// <auto-generated />
namespace EFarming.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Converting_Double_To_String_Productivity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Converting_Double_To_String_Productivity));
        
        string IMigrationMetadata.Id
        {
            get { return "201607121316192_Converting_Double_To_String_Productivity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
