// <auto-generated />
namespace EFarming.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddingLotReferencesForTheShipment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingLotReferencesForTheShipment));
        
        string IMigrationMetadata.Id
        {
            get { return "201601261333214_AddingLotReferencesForTheShipment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
