// <auto-generated />
namespace EFarming.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class DeletingInvoiceInLot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeletingInvoiceInLot));
        
        string IMigrationMetadata.Id
        {
            get { return "201604151917115_DeletingInvoiceInLot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
