// <auto-generated />
namespace EFarming.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Addingrelationshipmanytomanybetweenuserandproject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addingrelationshipmanytomanybetweenuserandproject));
        
        string IMigrationMetadata.Id
        {
            get { return "201712011900389_Adding relationship many to many between user and project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
