// <auto-generated />
namespace EFarming.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addestimetedproductionmanualfieldtoPlantationsentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addestimetedproductionmanualfieldtoPlantationsentity));
        
        string IMigrationMetadata.Id
        {
            get { return "202102101324027_add estimetedproductionmanual field to Plantations entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
