//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFarming.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFarming.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brother.
        /// </summary>
        internal static string Brother {
            get {
                return ResourceManager.GetString("Brother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Daugther.
        /// </summary>
        internal static string Daugther {
            get {
                return ResourceManager.GetString("Daugther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divorced.
        /// </summary>
        internal static string Divorced {
            get {
                return ResourceManager.GetString("Divorced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elemetary School.
        /// </summary>
        internal static string Elementary {
            get {
                return ResourceManager.GetString("Elementary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a High School.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Husband.
        /// </summary>
        internal static string Husband {
            get {
                return ResourceManager.GetString("Husband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Married.
        /// </summary>
        internal static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nephew.
        /// </summary>
        internal static string Nephew {
            get {
                return ResourceManager.GetString("Nephew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Niece.
        /// </summary>
        internal static string Niece {
            get {
                return ResourceManager.GetString("Niece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profesional.
        /// </summary>
        internal static string Profesional {
            get {
                return ResourceManager.GetString("Profesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Single.
        /// </summary>
        internal static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sister.
        /// </summary>
        internal static string Sister {
            get {
                return ResourceManager.GetString("Sister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Son.
        /// </summary>
        internal static string Son {
            get {
                return ResourceManager.GetString("Son", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Technician.
        /// </summary>
        internal static string Technician {
            get {
                return ResourceManager.GetString("Technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Widow.
        /// </summary>
        internal static string Widow {
            get {
                return ResourceManager.GetString("Widow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wife.
        /// </summary>
        internal static string Wife {
            get {
                return ResourceManager.GetString("Wife", resourceCulture);
            }
        }
    }
}
