//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFarming.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminMessage() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFarming.Common.Resources.AdminMessage", typeof(AdminMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobar.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cooperativa.
        /// </summary>
        public static string Cooperative {
            get {
                return ResourceManager.GetString("Cooperative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cooperativas.
        /// </summary>
        public static string Cooperatives {
            get {
                return ResourceManager.GetString("Cooperatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear una Cooperativa.
        /// </summary>
        public static string Create_New_Cooperative {
            get {
                return ResourceManager.GetString("Create_New_Cooperative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear un Departamento.
        /// </summary>
        public static string Create_New_Department {
            get {
                return ResourceManager.GetString("Create_New_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear un nuevo Estado de finca.
        /// </summary>
        public static string Create_New_Farm_Status {
            get {
                return ResourceManager.GetString("Create_New_Farm_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear un nuevo subestatus de finca.
        /// </summary>
        public static string Create_New_Farm_Substatus {
            get {
                return ResourceManager.GetString("Create_New_Farm_Substatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear calificación del periodo de floración.
        /// </summary>
        public static string Create_New_Flowering_Period_Qualification {
            get {
                return ResourceManager.GetString("Create_New_Flowering_Period_Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Municipio.
        /// </summary>
        public static string Create_New_Municipality {
            get {
                return ResourceManager.GetString("Create_New_Municipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear otras actividades.
        /// </summary>
        public static string Create_New_Other_Activity {
            get {
                return ResourceManager.GetString("Create_New_Other_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear tipo de tenencia.
        /// </summary>
        public static string Create_New_Ownership_Type {
            get {
                return ResourceManager.GetString("Create_New_Ownership_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear estado de plantación.
        /// </summary>
        public static string Create_New_Plantation_Status {
            get {
                return ResourceManager.GetString("Create_New_Plantation_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear tipo de plantación.
        /// </summary>
        public static string Create_New_Plantation_Type {
            get {
                return ResourceManager.GetString("Create_New_Plantation_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear variedad de plantación.
        /// </summary>
        public static string Create_New_Plantation_Variety {
            get {
                return ResourceManager.GetString("Create_New_Plantation_Variety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear tipo de suelo.
        /// </summary>
        public static string Create_New_Soil_Type {
            get {
                return ResourceManager.GetString("Create_New_Soil_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear vereda.
        /// </summary>
        public static string Create_New_Village {
            get {
                return ResourceManager.GetString("Create_New_Village", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Denegar.
        /// </summary>
        public static string Deny {
            get {
                return ResourceManager.GetString("Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departamento.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departamentos.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de la finca.
        /// </summary>
        public static string Farm_Status {
            get {
                return ResourceManager.GetString("Farm_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estados de la finca.
        /// </summary>
        public static string Farm_Statuses {
            get {
                return ResourceManager.GetString("Farm_Statuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subestado de la finca.
        /// </summary>
        public static string Farm_Substatus {
            get {
                return ResourceManager.GetString("Farm_Substatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subestados de la finca.
        /// </summary>
        public static string Farm_Substatuses {
            get {
                return ResourceManager.GetString("Farm_Substatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fincas.
        /// </summary>
        public static string Farms {
            get {
                return ResourceManager.GetString("Farms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calificación del periodo de floración.
        /// </summary>
        public static string Flowering_Period_Qualification {
            get {
                return ResourceManager.GetString("Flowering_Period_Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calificaciónes del periodo de floración.
        /// </summary>
        public static string Flowering_Period_Qualifications {
            get {
                return ResourceManager.GetString("Flowering_Period_Qualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipios.
        /// </summary>
        public static string Municipalities {
            get {
                return ResourceManager.GetString("Municipalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio.
        /// </summary>
        public static string Municipality {
            get {
                return ResourceManager.GetString("Municipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otras actividades.
        /// </summary>
        public static string Other_Activities {
            get {
                return ResourceManager.GetString("Other_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otra actividad.
        /// </summary>
        public static string Other_Activity {
            get {
                return ResourceManager.GetString("Other_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de tenencia.
        /// </summary>
        public static string Ownership_Type {
            get {
                return ResourceManager.GetString("Ownership_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de tenencia.
        /// </summary>
        public static string Ownership_Types {
            get {
                return ResourceManager.GetString("Ownership_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios pendientes.
        /// </summary>
        public static string Pending_Users {
            get {
                return ResourceManager.GetString("Pending_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de la plantación.
        /// </summary>
        public static string Plantation_Status {
            get {
                return ResourceManager.GetString("Plantation_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estados de la plantación.
        /// </summary>
        public static string Plantation_Statuses {
            get {
                return ResourceManager.GetString("Plantation_Statuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de plantación.
        /// </summary>
        public static string Plantation_Type {
            get {
                return ResourceManager.GetString("Plantation_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de plantación.
        /// </summary>
        public static string Plantation_Types {
            get {
                return ResourceManager.GetString("Plantation_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variedades.
        /// </summary>
        public static string Plantation_Varieties {
            get {
                return ResourceManager.GetString("Plantation_Varieties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variedad.
        /// </summary>
        public static string Plantation_Variety {
            get {
                return ResourceManager.GetString("Plantation_Variety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productividad.
        /// </summary>
        public static string Productivity {
            get {
                return ResourceManager.GetString("Productivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de suelo.
        /// </summary>
        public static string Soil_Type {
            get {
                return ResourceManager.GetString("Soil_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de suelo.
        /// </summary>
        public static string Soil_Types {
            get {
                return ResourceManager.GetString("Soil_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de usuarios.
        /// </summary>
        public static string Ulers_List {
            get {
                return ResourceManager.GetString("Ulers_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vereda.
        /// </summary>
        public static string Village {
            get {
                return ResourceManager.GetString("Village", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Veredas.
        /// </summary>
        public static string Villages {
            get {
                return ResourceManager.GetString("Villages", resourceCulture);
            }
        }
    }
}
