//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFarming.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardMessage() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFarming.Common.Resources.DashboardMessage", typeof(DashboardMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicador de Edad.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sacos.
        /// </summary>
        public static string Bags {
            get {
                return ResourceManager.GetString("Bags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Performance.
        /// </summary>
        public static string Current_Performance {
            get {
                return ResourceManager.GetString("Current_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a indicador de densidad.
        /// </summary>
        public static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar finca.
        /// </summary>
        public static string Edit_Farm {
            get {
                return ResourceManager.GetString("Edit_Farm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producción estimada.
        /// </summary>
        public static string Estimated_Production {
            get {
                return ResourceManager.GetString("Estimated_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Performance por país.
        /// </summary>
        public static string Evolution_By_Country {
            get {
                return ResourceManager.GetString("Evolution_By_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Performance por finca.
        /// </summary>
        public static string Evolution_By_Farm {
            get {
                return ResourceManager.GetString("Evolution_By_Farm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Performance por proveedor.
        /// </summary>
        public static string Evolution_By_Supplier {
            get {
                return ResourceManager.GetString("Evolution_By_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Performance por cadena de suministro.
        /// </summary>
        public static string Evolution_By_Supplier_Chain {
            get {
                return ResourceManager.GetString("Evolution_By_Supplier_Chain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Performance.
        /// </summary>
        public static string Evolution_Performance {
            get {
                return ResourceManager.GetString("Evolution_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dasboard de finca.
        /// </summary>
        public static string Farm_Dashboard {
            get {
                return ResourceManager.GetString("Farm_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de fincas.
        /// </summary>
        public static string Farms_Per_Location {
            get {
                return ResourceManager.GetString("Farms_Per_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicador de fertilizantes.
        /// </summary>
        public static string Fertilizers {
            get {
                return ResourceManager.GetString("Fertilizers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GAP.
        /// </summary>
        public static string GAP {
            get {
                return ResourceManager.GetString("GAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GAP por país.
        /// </summary>
        public static string GAP_By_Country {
            get {
                return ResourceManager.GetString("GAP_By_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GAP por proveedor.
        /// </summary>
        public static string GAP_By_Supplier {
            get {
                return ResourceManager.GetString("GAP_By_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GAP por cadena de suministro.
        /// </summary>
        public static string GAP_By_SupplierChain {
            get {
                return ResourceManager.GetString("GAP_By_SupplierChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir al Dashboard.
        /// </summary>
        public static string GoTo_Dashboard {
            get {
                return ResourceManager.GetString("GoTo_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a evolución de cadena de suministro.
        /// </summary>
        public static string GoTo_SupplierChain_Evolution {
            get {
                return ResourceManager.GetString("GoTo_SupplierChain_Evolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a Overview de cadena de suministro.
        /// </summary>
        public static string GoTo_SupplierChain_Overview {
            get {
                return ResourceManager.GetString("GoTo_SupplierChain_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Performance objetivo.
        /// </summary>
        public static string Ideal_Performance {
            get {
                return ResourceManager.GetString("Ideal_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Performance Sostenibilidad.
        /// </summary>
        public static string Impact_Performance {
            get {
                return ResourceManager.GetString("Impact_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguimiento de sostenibilidad {0}.
        /// </summary>
        public static string Impact_Track {
            get {
                return ResourceManager.GetString("Impact_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a # de sacos de fertilizante.
        /// </summary>
        public static string Number_Fertilizer_Bags {
            get {
                return ResourceManager.GetString("Number_Fertilizer_Bags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a # de Hectáreas.
        /// </summary>
        public static string Number_Hectares {
            get {
                return ResourceManager.GetString("Number_Hectares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de fincas.
        /// </summary>
        public static string Number_Of_Farms {
            get {
                return ResourceManager.GetString("Number_Of_Farms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a # de plantas.
        /// </summary>
        public static string Number_Plants {
            get {
                return ResourceManager.GetString("Number_Plants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a # de plantas productivas.
        /// </summary>
        public static string Number_Productive_Plants {
            get {
                return ResourceManager.GetString("Number_Productive_Plants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overview por país.
        /// </summary>
        public static string Overview_By_Country {
            get {
                return ResourceManager.GetString("Overview_By_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overview por finca.
        /// </summary>
        public static string Overview_By_Farm {
            get {
                return ResourceManager.GetString("Overview_By_Farm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overview by Supplier.
        /// </summary>
        public static string Overview_By_Supplier {
            get {
                return ResourceManager.GetString("Overview_By_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overview por cadena de suministro.
        /// </summary>
        public static string Overview_By_Supplier_Chain {
            get {
                return ResourceManager.GetString("Overview_By_Supplier_Chain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overview.
        /// </summary>
        public static string Overview_Performance {
            get {
                return ResourceManager.GetString("Overview_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución del tipo de tenencia.
        /// </summary>
        public static string Ownership_Type {
            get {
                return ResourceManager.GetString("Ownership_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        public static string Plantation_Information {
            get {
                return ResourceManager.GetString("Plantation_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plantaciones por ubicación.
        /// </summary>
        public static string Plantations_Per_Location {
            get {
                return ResourceManager.GetString("Plantations_Per_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Potencial.
        /// </summary>
        public static string Potencial {
            get {
                return ResourceManager.GetString("Potencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicador de productividad.
        /// </summary>
        public static string Productivity {
            get {
                return ResourceManager.GetString("Productivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Performance en calidad.
        /// </summary>
        public static string Quality_Performance {
            get {
                return ResourceManager.GetString("Quality_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución de fincas por tamaño.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GAP Sostenibilidad.
        /// </summary>
        public static string Sustainability_GAP {
            get {
                return ResourceManager.GetString("Sustainability_GAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Performance de sostenibilidad.
        /// </summary>
        public static string Sustainability_Performance {
            get {
                return ResourceManager.GetString("Sustainability_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área total.
        /// </summary>
        public static string Total_Area {
            get {
                return ResourceManager.GetString("Total_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área total de lotes.
        /// </summary>
        public static string Total_Plantation_Area {
            get {
                return ResourceManager.GetString("Total_Plantation_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución de variedades.
        /// </summary>
        public static string Variety {
            get {
                return ResourceManager.GetString("Variety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volumen de ventas.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evolución del volumen de ventas.
        /// </summary>
        public static string Volume_Evolution {
            get {
                return ResourceManager.GetString("Volume_Evolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volumen de ventas (Kgs).
        /// </summary>
        public static string Volume_Tons {
            get {
                return ResourceManager.GetString("Volume_Tons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución de trabajadores.
        /// </summary>
        public static string Workers {
            get {
                return ResourceManager.GetString("Workers", resourceCulture);
            }
        }
    }
}
