//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFarming.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FarmMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FarmMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFarming.Common.Resources.FarmMessages", typeof(FarmMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar fertilizante.
        /// </summary>
        public static string Add_Fertlizer {
            get {
                return ResourceManager.GetString("Add_Fertlizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar periodo de floración.
        /// </summary>
        public static string Add_Flowering_Period {
            get {
                return ResourceManager.GetString("Add_Flowering_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar otra actividad.
        /// </summary>
        public static string Add_Other_Activity {
            get {
                return ResourceManager.GetString("Add_Other_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar lote.
        /// </summary>
        public static string Add_Plantation {
            get {
                return ResourceManager.GetString("Add_Plantation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personas asociadas.
        /// </summary>
        public static string Associated_People {
            get {
                return ResourceManager.GetString("Associated_People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hectáreas en conservación.
        /// </summary>
        public static string Conservation_Hectares {
            get {
                return ResourceManager.GetString("Conservation_Hectares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear una nueva finca.
        /// </summary>
        public static string Create_New_Farm {
            get {
                return ResourceManager.GetString("Create_New_Farm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Depth.
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Finca.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finca {0} - {1}.
        /// </summary>
        public static string Edit_Farm {
            get {
                return ResourceManager.GetString("Edit_Farm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producción estimada.
        /// </summary>
        public static string Estimated_Production {
            get {
                return ResourceManager.GetString("Estimated_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad familiar.
        /// </summary>
        public static string Family_Unit {
            get {
                return ResourceManager.GetString("Family_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finca.
        /// </summary>
        public static string Farm {
            get {
                return ResourceManager.GetString("Farm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información básica.
        /// </summary>
        public static string Farm_Basic_info {
            get {
                return ResourceManager.GetString("Farm_Basic_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de finca.
        /// </summary>
        public static string Farm_Info {
            get {
                return ResourceManager.GetString("Farm_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación.
        /// </summary>
        public static string Farm_location {
            get {
                return ResourceManager.GetString("Farm_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fincas.
        /// </summary>
        public static string Farms {
            get {
                return ResourceManager.GetString("Farms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fertlizante.
        /// </summary>
        public static string Fertilizer {
            get {
                return ResourceManager.GetString("Fertilizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fertlizantes.
        /// </summary>
        public static string Fertilizers {
            get {
                return ResourceManager.GetString("Fertilizers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodo de floración.
        /// </summary>
        public static string Flowering_Period {
            get {
                return ResourceManager.GetString("Flowering_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodos de floración.
        /// </summary>
        public static string Flowering_Periods {
            get {
                return ResourceManager.GetString("Flowering_Periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hectáreas en bosque protegido.
        /// </summary>
        public static string Forest_Protected_Hectares {
            get {
                return ResourceManager.GetString("Forest_Protected_Hectares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hectáreas.
        /// </summary>
        public static string Hectares {
            get {
                return ResourceManager.GetString("Hectares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hectáreas en infrastructura.
        /// </summary>
        public static string Infrastructure_Hectares {
            get {
                return ResourceManager.GetString("Infrastructure_Hectares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de finca.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo lote.
        /// </summary>
        public static string New_Plantation {
            get {
                return ResourceManager.GetString("New_Plantation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron fotos.
        /// </summary>
        public static string No_Photos_Found {
            get {
                return ResourceManager.GetString("No_Photos_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de plantas.
        /// </summary>
        public static string Number_Of_Plants {
            get {
                return ResourceManager.GetString("Number_Of_Plants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de plantas productivas.
        /// </summary>
        public static string Number_Of_Productive_Plants {
            get {
                return ResourceManager.GetString("Number_Of_Productive_Plants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otras actividades.
        /// </summary>
        public static string Other_Activities {
            get {
                return ResourceManager.GetString("Other_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propietario.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PCC2015.
        /// </summary>
        public static string PCC2015 {
            get {
                return ResourceManager.GetString("PCC2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a trabajadores {0} permanentes.
        /// </summary>
        public static string Permanent_Workers {
            get {
                return ResourceManager.GetString("Permanent_Workers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Galería de fotos.
        /// </summary>
        public static string Photo_Gallery {
            get {
                return ResourceManager.GetString("Photo_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lotes.
        /// </summary>
        public static string Plantations {
            get {
                return ResourceManager.GetString("Plantations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productividad.
        /// </summary>
        public static string Productivity {
            get {
                return ResourceManager.GetString("Productivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de productividad.
        /// </summary>
        public static string Productivity_Information {
            get {
                return ResourceManager.GetString("Productivity_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar fincas.
        /// </summary>
        public static string Search_Farms {
            get {
                return ResourceManager.GetString("Search_Farms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Establecer como principal.
        /// </summary>
        public static string Set_Primary {
            get {
                return ResourceManager.GetString("Set_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porcentaje de sombra.
        /// </summary>
        public static string Shading_Percentage {
            get {
                return ResourceManager.GetString("Shading_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Análisis de suelo.
        /// </summary>
        public static string Soil_Analysis {
            get {
                return ResourceManager.GetString("Soil_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de tipo de suelos.
        /// </summary>
        public static string Soil_Types_Information {
            get {
                return ResourceManager.GetString("Soil_Types_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TASQ.
        /// </summary>
        public static string TASQ {
            get {
                return ResourceManager.GetString("TASQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Técnico.
        /// </summary>
        public static string Technician {
            get {
                return ResourceManager.GetString("Technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trabajadores {0} temporales.
        /// </summary>
        public static string Temporary_Workers {
            get {
                return ResourceManager.GetString("Temporary_Workers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fincas.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hectáreas totales.
        /// </summary>
        public static string Total_Hectares {
            get {
                return ResourceManager.GetString("Total_Hectares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trabajadores.
        /// </summary>
        public static string Workers {
            get {
                return ResourceManager.GetString("Workers", resourceCulture);
            }
        }
    }
}
