//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFarming.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndicatorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndicatorMessage() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFarming.Common.Resources.IndicatorMessage", typeof(IndicatorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorías.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear nueva encuesta.
        /// </summary>
        public static string Create_New {
            get {
                return ResourceManager.GetString("Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar categoría.
        /// </summary>
        public static string Edit_Category {
            get {
                return ResourceManager.GetString("Edit_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sostenibilidad en finca.
        /// </summary>
        public static string Farm_Impact {
            get {
                return ResourceManager.GetString("Farm_Impact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuesta de sostenibilidad.
        /// </summary>
        public static string Impact_Assessment {
            get {
                return ResourceManager.GetString("Impact_Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicadores de Sostenibilidad.
        /// </summary>
        public static string Impact_Indicators {
            get {
                return ResourceManager.GetString("Impact_Indicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a KPI.
        /// </summary>
        public static string KPI {
            get {
                return ResourceManager.GetString("KPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criterio de carga.
        /// </summary>
        public static string Load_Criteria {
            get {
                return ResourceManager.GetString("Load_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a obligatorio.
        /// </summary>
        public static string Mandatory {
            get {
                return ResourceManager.GetString("Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva categoría.
        /// </summary>
        public static string New_Category {
            get {
                return ResourceManager.GetString("New_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo criterio.
        /// </summary>
        public static string New_Criteria {
            get {
                return ResourceManager.GetString("New_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva encuesta de calidad.
        /// </summary>
        public static string New_Impact_Assessment {
            get {
                return ResourceManager.GetString("New_Impact_Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo indicador.
        /// </summary>
        public static string New_Indicator {
            get {
                return ResourceManager.GetString("New_Indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar respuestas.
        /// </summary>
        public static string Save_Answers {
            get {
                return ResourceManager.GetString("Save_Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver opciones.
        /// </summary>
        public static string View_Options {
            get {
                return ResourceManager.GetString("View_Options", resourceCulture);
            }
        }
    }
}
