//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFarming.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QualityMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QualityMessage() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFarming.Common.Resources.QualityMessage", typeof(QualityMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar atributo de calidad.
        /// </summary>
        public static string Add_New_attribute {
            get {
                return ResourceManager.GetString("Add_New_attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar opción.
        /// </summary>
        public static string Add_New_Option {
            get {
                return ResourceManager.GetString("Add_New_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuesta.
        /// </summary>
        public static string Assessment_Template {
            get {
                return ResourceManager.GetString("Assessment_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a información básica.
        /// </summary>
        public static string Basic_Information {
            get {
                return ResourceManager.GetString("Basic_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de chequeo.
        /// </summary>
        public static string Checklist {
            get {
                return ResourceManager.GetString("Checklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listas de chequeo.
        /// </summary>
        public static string Checklists {
            get {
                return ResourceManager.GetString("Checklists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se lleva algun control en el proceso de recolección.
        /// </summary>
        public static string Control_Proceso_Recoleccion {
            get {
                return ResourceManager.GetString("Control_Proceso_Recoleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear o editar atributos de calidad.
        /// </summary>
        public static string Create_Edit_Attribute {
            get {
                return ResourceManager.GetString("Create_Edit_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva encuesta de análisis sensorial.
        /// </summary>
        public static string Create_New_Assessment {
            get {
                return ResourceManager.GetString("Create_New_Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear una lista de checqueo.
        /// </summary>
        public static string Create_New_Checklist {
            get {
                return ResourceManager.GetString("Create_New_Checklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cual es su criterio para identificar que el café esta en su punto de lavado.
        /// </summary>
        public static string Criterio_Identificacion_Lavado {
            get {
                return ResourceManager.GetString("Criterio_Identificacion_Lavado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta cuantas.
        /// </summary>
        public static string Cuantas_Cochadas {
            get {
                return ResourceManager.GetString("Cuantas_Cochadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a De cuantos días.
        /// </summary>
        public static string Cuantos_Dias_Cochadas {
            get {
                return ResourceManager.GetString("Cuantos_Dias_Cochadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dashboard calidad.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dashboard de calidad por Cooperativa.
        /// </summary>
        public static string DashboardByCooperative {
            get {
                return ResourceManager.GetString("DashboardByCooperative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar encuesta de calidad.
        /// </summary>
        public static string Delete_Quality_Assessment {
            get {
                return ResourceManager.GetString("Delete_Quality_Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Despulpado.
        /// </summary>
        public static string Despulpado {
            get {
                return ResourceManager.GetString("Despulpado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fermentacion.
        /// </summary>
        public static string Fermentacion {
            get {
                return ResourceManager.GetString("Fermentacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a De donde proviene el agua que se  utiliza en el proceso de beneficio.
        /// </summary>
        public static string Fuente_Agua {
            get {
                return ResourceManager.GetString("Fuente_Agua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es número?.
        /// </summary>
        public static string Is_Number {
            get {
                return ResourceManager.GetString("Is_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Junta café de diferentes cochadas durante la fermentación.
        /// </summary>
        public static string Junta_En_Cochadas {
            get {
                return ResourceManager.GetString("Junta_En_Cochadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lava el café inmediatamente despues de  fermentado.
        /// </summary>
        public static string Lava_Despues_Fermentado {
            get {
                return ResourceManager.GetString("Lava_Despues_Fermentado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hecho por.
        /// </summary>
        public static string Made_By {
            get {
                return ResourceManager.GetString("Made_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % Maduros.
        /// </summary>
        public static string Maduros {
            get {
                return ResourceManager.GetString("Maduros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maneja Tolva sifon como un sistema de clasificacion.
        /// </summary>
        public static string Maneja_Sistema_Clasificacion {
            get {
                return ResourceManager.GetString("Maneja_Sistema_Clasificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material del tanque de fermentación.
        /// </summary>
        public static string Material_Tanque {
            get {
                return ResourceManager.GetString("Material_Tanque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor máximo.
        /// </summary>
        public static string MaxVal {
            get {
                return ResourceManager.GetString("MaxVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Microlote.
        /// </summary>
        public static string Microlot {
            get {
                return ResourceManager.GetString("Microlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor mínimo.
        /// </summary>
        public static string MinVal {
            get {
                return ResourceManager.GetString("MinVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto.
        /// </summary>
        public static string OpenText {
            get {
                return ResourceManager.GetString("OpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} Opciones.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La despulpadora deja pasar al tanque de fermentación pulpa.
        /// </summary>
        public static string Pasa_Fermentacion {
            get {
                return ResourceManager.GetString("Pasa_Fermentacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % Pintones.
        /// </summary>
        public static string Pintones {
            get {
                return ResourceManager.GetString("Pintones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuesta de calidad.
        /// </summary>
        public static string Quality_Assessment {
            get {
                return ResourceManager.GetString("Quality_Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atributos de calidad.
        /// </summary>
        public static string Quality_Attributes {
            get {
                return ResourceManager.GetString("Quality_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil de calidad.
        /// </summary>
        public static string Quality_Profile {
            get {
                return ResourceManager.GetString("Quality_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango {0} - {1} ({2}).
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recolección.
        /// </summary>
        public static string Recoleccion {
            get {
                return ResourceManager.GetString("Recoleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar encuesta de calidad.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil sensorial.
        /// </summary>
        public static string Sensory_Profile {
            get {
                return ResourceManager.GetString("Sensory_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuesta de perfil sensorial.
        /// </summary>
        public static string Sensory_Profile_Assessment {
            get {
                return ResourceManager.GetString("Sensory_Profile_Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Implementa algùn sistema de clasificaciòn del cafè en el momento de despulpado (Ej: Zaranda).
        /// </summary>
        public static string Sistema_Clasificacion {
            get {
                return ResourceManager.GetString("Sistema_Clasificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema de fermentación  aplicado en la finca.
        /// </summary>
        public static string Sistema_Fermentacion {
            get {
                return ResourceManager.GetString("Sistema_Fermentacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % Sobremaduros.
        /// </summary>
        public static string Sobremaduros {
            get {
                return ResourceManager.GetString("Sobremaduros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catador.
        /// </summary>
        public static string Taster {
            get {
                return ResourceManager.GetString("Taster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo de fermentacion.
        /// </summary>
        public static string Tiempo_Fermentacion {
            get {
                return ResourceManager.GetString("Tiempo_Fermentacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo transcurrido entre el recibo y el inicio del despulpado.
        /// </summary>
        public static string Tiempo_Transcurrido_Despulpado {
            get {
                return ResourceManager.GetString("Tiempo_Transcurrido_Despulpado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Que tipo de beneficiadero utiliza.
        /// </summary>
        public static string Tipo_Beneficiadero {
            get {
                return ResourceManager.GetString("Tipo_Beneficiadero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realiza despulpado con agua.
        /// </summary>
        public static string Utiliza_Agua {
            get {
                return ResourceManager.GetString("Utiliza_Agua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % Verdes.
        /// </summary>
        public static string Verdes {
            get {
                return ResourceManager.GetString("Verdes", resourceCulture);
            }
        }
    }
}
